# Setup
name: 
  Tec-Blog
tagline: 
  blog
baseurl: 
  "https://kdkrkwhr.github.io"
locale: 
  "ko"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: 
  kramdown

disqus_shortname: 'https-kdkrkwhr-github-io'

disqus-identifier: 
  https-kdkrkwhr-github-io

comments:
  disqus:
    shortname: https-kdkrkwhr-github-io

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-PEYQZC0NSH"
    anonymize_ip         : # true, false (default)
